plugins {
    id "com.android.application"
}

android {
    namespace "com.userio.smsagent"
    compileSdk 34

    defaultConfig {
        applicationId "com.userio.smsagent"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
